# Generated by Django 4.0.6 on 2022-07-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productoption_remove_product_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='product',
        ),
        migrations.AddField(
            model_name='option',
            name='products',
            field=models.ManyToManyField(related_name='options', through='products.ProductOption', to='products.product'),
        ),
    ]
